---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: jdbc-source-connector
  namespace: confluent
spec:
  class: "io.confluent.connect.jdbc.JdbcSourceConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    connection.url: "jdbc:postgresql://postgres:5432/demo?user=test&password=test1234"
    topic.prefix: "jdbc-source-newtopic-"
    mode: "incrementing"
    incrementing.column.name: "id"
    #    timestamp.column.name: "modified"
    poll.interval.ms: "1000"
    table.whitelist: "mytopic"
    

---    
